version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "220820"
      POSTGRES_USER: postgres
      POSTGRES_DB: Botchat
  app:
    build: .
    ports:
      - "15000:5000"
